// Asset-catalog generator (Track A1).
//
// A headless tool that walks the prop registry, bakes each prop's voxel volume
// (no GL upload — links against the GL stub like the test build), measures its
// tight bounding box and voxel count, and emits a Markdown catalog. The catalog
// is a reference for world-population work: when furnishing a dungeon or house
// you can look up which props exist, how big they are, and how they behave.
//
// Build + run:  make catalog   (writes docs/ASSET_CATALOG.md)

#include "prop_registry.h"
#include "voxel_model.h"
#include "interactable.h"

#include <algorithm>
#include <cstdio>
#include <memory>

namespace {

const char* interactName(InteractAction a) {
    switch (a) {
        case InteractAction::SitChair: return "Sit";
        case InteractAction::LieBed:   return "Lie down";
        default:                       return "-";
    }
}

// Tight footprint of the non-empty (alpha > 0) voxels.
struct Footprint {
    int w = 0, d = 0, h = 0;   // X (width), Z (depth), Y (height)
    long count = 0;            // number of filled voxels
};

Footprint measure(const VoxelVolume* v) {
    Footprint f;
    int minx = v->sizeX, miny = v->sizeY, minz = v->sizeZ;
    int maxx = -1, maxy = -1, maxz = -1;
    for (int x = 0; x < v->sizeX; ++x)
        for (int y = 0; y < v->sizeY; ++y)
            for (int z = 0; z < v->sizeZ; ++z) {
                if (v->getVoxel(x, y, z).a == 0) continue;
                ++f.count;
                minx = std::min(minx, x); maxx = std::max(maxx, x);
                miny = std::min(miny, y); maxy = std::max(maxy, y);
                minz = std::min(minz, z); maxz = std::max(maxz, z);
            }
    if (f.count > 0) {
        f.w = maxx - minx + 1;
        f.h = maxy - miny + 1;
        f.d = maxz - minz + 1;
    }
    return f;
}

}  // namespace

int main(int argc, char** argv) {
    const char* outPath = (argc > 1) ? argv[1] : "docs/ASSET_CATALOG.md";

    FILE* out = std::fopen(outPath, "w");
    if (!out) {
        std::fprintf(stderr, "asset_catalog: cannot open %s for writing\n", outPath);
        return 1;
    }

    const auto& reg = propRegistry();

    std::fprintf(out,
        "# Terrax Asset Catalog — Props\n\n"
        "_Generated by `make catalog` (tools/asset_catalog.cpp). Do not edit by hand._\n\n"
        "Every entry in the prop registry, with its **footprint** (tight bounding\n"
        "box of filled voxels, in model-grid units: W = X, D = Z, H = Y), filled\n"
        "voxel count, and behaviour metadata. Use this when furnishing dungeons,\n"
        "houses and towns so you pick props that fit the space and behave right.\n\n"
        "| # | Prop | W×D×H | Voxels | Interact | Emits light | Sways |\n"
        "|--:|------|:-----:|-------:|:--------:|:-----------:|:-----:|\n");

    long totalVox = 0;
    int rows = 0;
    for (const auto& def : reg) {
        std::unique_ptr<VoxelVolume> v(def.build ? def.build() : nullptr);
        Footprint f = v ? measure(v.get()) : Footprint{};
        totalVox += f.count;
        ++rows;
        std::fprintf(out, "| %d | %s | %d×%d×%d | %ld | %s | %s | %s |\n",
                     (int)def.type, def.name, f.w, f.d, f.h, f.count,
                     interactName(def.interact.action),
                     def.light.emits ? (def.light.nightOnly ? "night" : "yes") : "-",
                     def.swaysInWind ? "yes" : "-");
    }

    std::fprintf(out, "\n**%d props · %ld filled voxels total.**\n", rows, totalVox);
    std::fclose(out);

    std::printf("asset_catalog: wrote %d props to %s\n", rows, outPath);
    return 0;
}
